// <auto-generated />
using EMP_BACKEND.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMP_BACKEND.Migrations
{
    [DbContext(typeof(DepartmentContext))]
    partial class DepartmentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMP_BACKEND.Models.Department", b =>
                {
                    b.Property<string>("Dcode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Dname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Dcode");

                    b.ToTable("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
